/**
 * web3-auth-svc — OPNet ML-DSA auth service for libpam-web3.
 *
 * Self-contained HTTPS server: serves the signing page and handles
 * auth callbacks. Port is derived from the chain name via CRC32.
 * TLS uses the certs generated by the libpam-web3 postinst.
 *
 * Routes:
 *   GET  /              — Signing page HTML
 *   GET  /engine.js     — Signing page JS
 *   GET  /auth/pending/:session_id   — Return session JSON
 *   POST /auth/callback/:session_id  — Verify ML-DSA signature, write .sig file
 *
 * .sig file format (JSON):
 *   { chain, otp, machine_id, wallet_address }
 *   chain = "opnet" — tells the PAM module which verification plugin to use
 *   wallet_address = 0x + hex(SHA256(publicKey))
 *
 * SPECIAL profile: S7 P9 E8 C5 I7 A7 L7
 *   P9: Auth boundary — validate every input, trust nothing from the network.
 *   E8: Long-running daemon — must not crash, must not leak.
 *
 * Cryptographic verification:
 *   ML-DSA signatures (44/65/87) are verified before writing .sig files.
 *   This is a safety check (not forged garbage), not an identity check —
 *   the PAM plugin handles identity binding.
 */

import * as https from "node:https";
import * as fs from "node:fs";
import * as path from "node:path";
import { createHash, timingSafeEqual } from "node:crypto";
import { ml_dsa44, ml_dsa65, ml_dsa87 } from "@btc-vision/post-quantum/ml-dsa.js";
import { chainPort } from "./chain-port";

// ── Constants ──────────────────────────────────────────────────────────

const CHAIN_NAME = "opnet";
const DEFAULT_PENDING_DIR = "/run/libpam-web3/pending";
let PENDING_DIR = DEFAULT_PENDING_DIR;
const MAX_BODY_SIZE = 16_384;

const SESSION_ID_RE = /^[0-9a-f]{32}$/;
const BASE64_RE = /^[A-Za-z0-9+/]+=*$/;


// ── ML-DSA Parameter Tables ───────────────────────────────────────────

interface MLDSALevel {
  sigSize: number;
  verify: (sig: Uint8Array, msg: Uint8Array, publicKey: Uint8Array) => boolean;
  name: string;
}

/** Key: public key byte length. Value: expected signature size + verify function. */
const MLDSA_LEVELS: ReadonlyMap<number, MLDSALevel> = new Map([
  [1312, { sigSize: 2420, verify: ml_dsa44.verify, name: "ML-DSA-44" }],
  [1952, { sigSize: 3309, verify: ml_dsa65.verify, name: "ML-DSA-65" }],
  [2592, { sigSize: 4627, verify: ml_dsa87.verify, name: "ML-DSA-87" }],
]);

// ── Config ─────────────────────────────────────────────────────────────

const DEFAULT_CERT = "/etc/libpam-web3/tls/cert.pem";
const DEFAULT_KEY = "/etc/libpam-web3/tls/key.pem";
const DEFAULT_PAGES_DIR = "/usr/share/blockhost/signing-pages";

interface ServerConfig {
  port: number;
  pending_dir: string;
  cert: string;
  key: string;
  pages_dir: string;
}

function parseToml(content: string): Record<string, Record<string, unknown>> {
  const result: Record<string, Record<string, unknown>> = {};
  let section = "";

  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;

    const secMatch = line.match(/^\[([a-zA-Z_][a-zA-Z0-9_]*)\]$/);
    if (secMatch?.[1]) {
      section = secMatch[1];
      result[section] = result[section] || {};
      continue;
    }

    const kvMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.+)$/);
    if (!kvMatch?.[1] || !kvMatch[2] || !section) continue;

    const key = kvMatch[1];
    const val = kvMatch[2].trim();

    if (val.startsWith('"') && val.endsWith('"')) {
      result[section]![key] = val.slice(1, -1);
    } else {
      const num = Number(val);
      result[section]![key] = Number.isNaN(num) ? val : num;
    }
  }

  return result;
}

function loadConfig(configPath: string): ServerConfig {
  const defaultPort = chainPort(CHAIN_NAME);
  const defaults: ServerConfig = {
    port: defaultPort,
    pending_dir: DEFAULT_PENDING_DIR,
    cert: DEFAULT_CERT,
    key: DEFAULT_KEY,
    pages_dir: path.join(DEFAULT_PAGES_DIR, CHAIN_NAME),
  };

  let content: string;
  try {
    content = fs.readFileSync(configPath, "utf8");
  } catch {
    return defaults;
  }

  const toml = parseToml(content);
  const sec = toml["server"] || {};

  return {
    port: typeof sec.port === "number" ? sec.port : defaults.port,
    pending_dir: String(sec.pending_dir || defaults.pending_dir),
    cert: String(sec.cert || defaults.cert),
    key: String(sec.key || defaults.key),
    pages_dir: String(sec.pages_dir || defaults.pages_dir),
  };
}

// ── Validation & Decoding ─────────────────────────────────────────────

function isValidSessionId(id: string): boolean {
  return SESSION_ID_RE.test(id);
}

function decodeBase64(str: string): Buffer | null {
  if (!str || !BASE64_RE.test(str)) return null;
  const buf = Buffer.from(str, "base64");
  if (buf.length === 0) return null;
  return buf;
}

interface CallbackPayload {
  signature: string;
  publicKey: string;
  otp: string;
  machineId: string;
}

function parseCallbackBody(body: string): CallbackPayload | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(body);
  } catch {
    return null;
  }

  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    return null;
  }

  const obj = parsed as Record<string, unknown>;
  const keys = Object.keys(obj);

  if (keys.length !== 4) return null;
  if (typeof obj["signature"] !== "string") return null;
  if (typeof obj["publicKey"] !== "string") return null;
  if (typeof obj["otp"] !== "string") return null;
  if (typeof obj["machineId"] !== "string") return null;

  if (obj["otp"].length > 16 || obj["machineId"].length > 128) return null;

  return {
    signature: obj["signature"],
    publicKey: obj["publicKey"],
    otp: obj["otp"],
    machineId: obj["machineId"],
  };
}

interface SessionData {
  otp: string;
  machine_id: string;
}

function loadSession(sessionId: string): SessionData | null {
  const jsonPath = path.join(PENDING_DIR, `${sessionId}.json`);
  try {
    const content = fs.readFileSync(jsonPath, "utf8");
    const parsed: unknown = JSON.parse(content);
    if (typeof parsed !== "object" || parsed === null) return null;
    const obj = parsed as Record<string, unknown>;
    if (typeof obj["otp"] !== "string" || typeof obj["machine_id"] !== "string") {
      return null;
    }
    return { otp: obj["otp"], machine_id: obj["machine_id"] };
  } catch {
    return null;
  }
}

// ── ML-DSA Verification Pipeline ──────────────────────────────────────

function verifyAndWriteSig(sessionId: string, payload: CallbackPayload): string | null {
  const sigBytes = decodeBase64(payload.signature);
  const pubKeyBytes = decodeBase64(payload.publicKey);
  if (!sigBytes) return "invalid base64 in signature field";
  if (!pubKeyBytes) return "invalid base64 in publicKey field";

  const level = MLDSA_LEVELS.get(pubKeyBytes.length);
  if (!level) return `unrecognized public key size: ${pubKeyBytes.length} bytes`;

  if (sigBytes.length !== level.sigSize) {
    return `signature size ${sigBytes.length} does not match ${level.name} (expected ${level.sigSize})`;
  }

  const sigPath = path.join(PENDING_DIR, `${sessionId}.sig`);
  if (fs.existsSync(sigPath)) return "session already processed";

  const session = loadSession(sessionId);
  if (!session) return "session not found or malformed";

  const otpA = Buffer.from(payload.otp);
  const otpB = Buffer.from(session.otp);
  if (otpA.length !== otpB.length) return "otp mismatch";
  if (!timingSafeEqual(otpA, otpB)) return "otp mismatch";
  if (payload.machineId !== session.machine_id) return "machine_id mismatch";

  // Reconstruct signed message and double-hash per OPWallet convention:
  // signing page sends hex(SHA256(message)) to wallet.web3.signMLDSAMessage(),
  // wallet internally SHA256-hashes the hex string → signed data is SHA256(hex(SHA256(message)))
  const message = `Authenticate to ${payload.machineId} with code: ${payload.otp}`;
  const messageHash = createHash("sha256").update(message).digest();
  const walletInput = messageHash.toString("hex");
  const signedHash = createHash("sha256").update(walletInput).digest();

  let isValid: boolean;
  try {
    isValid = level.verify(
      new Uint8Array(sigBytes),
      new Uint8Array(signedHash),
      new Uint8Array(pubKeyBytes)
    );
  } catch (err) {
    return `${level.name} verify threw: ${err instanceof Error ? err.message : String(err)}`;
  }

  if (!isValid) return "signature verification failed";

  const walletAddress = "0x" + createHash("sha256").update(pubKeyBytes).digest("hex");

  const sigContent = JSON.stringify({
    chain: "opnet",
    otp: payload.otp,
    machine_id: payload.machineId,
    wallet_address: walletAddress,
  });

  const tmpPath = path.join(PENDING_DIR, `${sessionId}.sig.tmp`);
  try {
    fs.writeFileSync(tmpPath, sigContent);
    fs.renameSync(tmpPath, sigPath);
  } catch (err) {
    try { fs.unlinkSync(tmpPath); } catch { /* tmp may not exist */ }
    return `sig file write failed: ${err instanceof Error ? err.message : String(err)}`;
  }

  console.log(`[AUTH] Verified ${level.name} signature for session ${sessionId} → ${walletAddress}`);
  return null;
}

// ── Route Handlers ────────────────────────────────────────────────────

function sendResponse(
  res: import("node:http").ServerResponse,
  statusCode: number,
  body: string,
  contentType = "text/plain"
): void {
  res.writeHead(statusCode, { "Content-Type": contentType });
  res.end(body);
}

function handleGetPending(sessionId: string, res: import("node:http").ServerResponse): void {
  if (!isValidSessionId(sessionId)) {
    sendResponse(res, 404, "Not Found");
    return;
  }

  const jsonPath = path.join(PENDING_DIR, `${sessionId}.json`);
  let contents: string;
  try {
    contents = fs.readFileSync(jsonPath, "utf8");
  } catch {
    sendResponse(res, 404, "Not Found");
    return;
  }

  sendResponse(res, 200, contents, "application/json");
}

function handlePostCallback(
  sessionId: string,
  req: import("node:http").IncomingMessage,
  res: import("node:http").ServerResponse
): void {
  if (!isValidSessionId(sessionId)) {
    sendResponse(res, 404, "Not Found");
    return;
  }

  const contentType = req.headers["content-type"] || "";
  if (!contentType.includes("application/json")) {
    sendResponse(res, 400, "Content-Type must be application/json");
    return;
  }

  const chunks: Buffer[] = [];
  let bodySize = 0;
  let aborted = false;

  req.on("data", (chunk: Buffer) => {
    bodySize += chunk.length;
    if (bodySize > MAX_BODY_SIZE) {
      if (!aborted) {
        aborted = true;
        sendResponse(res, 413, "body too large");
        req.destroy();
      }
      return;
    }
    chunks.push(chunk);
  });

  req.on("end", () => {
    if (aborted) return;

    const body = Buffer.concat(chunks).toString("utf8").trim();
    const payload = parseCallbackBody(body);
    if (!payload) {
      sendResponse(res, 400, "invalid request body");
      return;
    }

    const error = verifyAndWriteSig(sessionId, payload);

    if (error === null) {
      sendResponse(res, 200, "OK");
    } else if (error === "session already processed") {
      sendResponse(res, 409, "Conflict");
    } else if (error === "session not found or malformed") {
      sendResponse(res, 404, "Not Found");
    } else {
      console.error(`[AUTH] Callback rejected for session ${sessionId}: ${error}`);
      sendResponse(res, 400, "verification failed");
    }
  });

  req.on("error", () => { /* connection closed by client */ });
}

// ── Static file serving ───────────────────────────────────────────────

let PAGES_DIR = "";

function serveFile(
  res: import("node:http").ServerResponse,
  filePath: string,
  contentType: string
): void {
  let data: Buffer;
  try {
    data = fs.readFileSync(filePath);
  } catch {
    sendResponse(res, 404, "Not Found");
    return;
  }
  res.writeHead(200, {
    "Content-Type": contentType,
    "Content-Length": data.length,
  });
  res.end(data);
}

// ── Server ────────────────────────────────────────────────────────────

function main(): void {
  const configPath = process.argv[2] || `/etc/web3-auth/${CHAIN_NAME}.toml`;
  const config = loadConfig(configPath);
  PENDING_DIR = config.pending_dir;
  PAGES_DIR = config.pages_dir;

  let tlsOpts: { cert: Buffer; key: Buffer };
  try {
    tlsOpts = {
      cert: fs.readFileSync(config.cert),
      key: fs.readFileSync(config.key),
    };
  } catch (err) {
    console.error(`[AUTH] TLS cert/key load failed: ${err}`);
    process.exit(1);
  }

  const server = https.createServer(tlsOpts, (req, res) => {
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.setHeader("Cache-Control", "no-store");

    const url = new URL(req.url || "/", "https://localhost");
    const pathname = url.pathname;

    // Signing page
    if (req.method === "GET" && (pathname === "/" || pathname === "/index.html")) {
      serveFile(res, path.join(PAGES_DIR, "index.html"), "text/html; charset=utf-8");
      return;
    }
    if (req.method === "GET" && pathname === "/engine.js") {
      serveFile(res, path.join(PAGES_DIR, "engine.js"), "application/javascript; charset=utf-8");
      return;
    }

    // Auth API
    const pendingMatch = pathname.match(/^\/auth\/pending\/([^/]+)$/);
    if (req.method === "GET" && pendingMatch?.[1]) {
      handleGetPending(pendingMatch[1], res);
      return;
    }

    const callbackMatch = pathname.match(/^\/auth\/callback\/([^/]+)$/);
    if (req.method === "POST" && callbackMatch?.[1]) {
      handlePostCallback(callbackMatch[1], req, res);
      return;
    }

    sendResponse(res, 404, "Not Found");
  });

  // Bind to all interfaces (dual-stack IPv6)
  server.listen(config.port, "::", () => {
    console.log(`[AUTH] web3-auth-svc (${CHAIN_NAME}) on [::]:${config.port}`);
    console.log(`[AUTH] Pending dir: ${PENDING_DIR}`);
    console.log(`[AUTH] Pages: ${PAGES_DIR}`);
  });

  server.on("error", (err) => {
    console.error(`[AUTH] Server error: ${err}`);
    process.exit(1);
  });

  process.on("SIGTERM", () => {
    console.log("[AUTH] Shutting down...");
    server.close(() => process.exit(0));
  });

  process.on("SIGINT", () => {
    console.log("[AUTH] Shutting down...");
    server.close(() => process.exit(0));
  });
}

// Only run as a server when invoked as the entry point (auth-svc.js or
// index.ts via tsx). When imported by a test file, skip — otherwise the
// test would try to load TLS certs and bind to a port.
if (process.argv[1]?.match(/\/(auth-svc\.js|index\.ts)$/)) {
  main();
}
